services:
  android-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    image: ${REGISTRY_BASE_URL}/${IMAGE_OWNER}/${IMAGE_NAME}:${IMAGE_TAG}
    runtime: nvidia
    network_mode: host
    #stdin_open: true        # Permette l'interazione con la shell
    #tty: true               # Mantiene la sessione aperta
    #command: ["/bin/bash"]
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=/run/user/${UID:-1000}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - QT_QPA_PLATFORM=xcb
      - CONTAINER_USERNAME=${CONTAINER_USERNAME}
    devices:
      - /dev/dri:/dev/dri
      - /dev/kvm:/dev/kvm
      - /dev/snd:/dev/snd
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    volumes:
      - /dev/kvm:/dev/kvm
      - /run/user/${PUID:-1000}/${WAYLAND_DISPLAY}:/run/user/${PUID:-1000}/${WAYLAND_DISPLAY}:ro
      - /run/user/${PUID:-1000}/pulse:/run/user/${PUID:-1000}/pulse:rw
      - /run/user/${PUID:-1000}/avd/running:/run/user/${PUID:-1000}/avd/running:rw
      - $PWD/mount/Android:/home/${CONTAINER_USERNAME:-PUID}/Android
      - $PWD/mount/.android:/home/${CONTAINER_USERNAME:-manzolo}/.android
      - $PWD/mount/.AndroidStudio:/home/${CONTAINER_USERNAME:-manzolo}/.AndroidStudio
      - $PWD/mount/StudioProjects:/home/${CONTAINER_USERNAME:-manzolo}/StudioProjects
      - $PWD/mount/.config/Google:/home/${CONTAINER_USERNAME:-manzolo}/.config/Google
      - $PWD/mount/.gradle:/home/${CONTAINER_USERNAME:-manzolo}/.gradle      
      - $PWD/mount/.cache/Google:/home/${CONTAINER_USERNAME:-manzolo}/.cache/Google
      - $PWD/mount/.java:/home/${CONTAINER_USERNAME:-manzolo}/.java
      - $PWD/mount/.local:/home/${CONTAINER_USERNAME:-manzolo}/.local
      - $PWD/mount/.ssh:/home/${CONTAINER_USERNAME:-manzolo}/.ssh

      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    shm_size: 2g
    security_opt:
      - seccomp=unconfined

