services:
  android-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: android-studio
    runtime: nvidia
    network_mode: host
    #stdin_open: true        # Permette l'interazione con la shell
    #tty: true               # Mantiene la sessione aperta
    #command: ["/bin/bash"]
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=/run/user/${UID:-1000}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - QT_QPA_PLATFORM=xcb
    devices:
      - /dev/dri:/dev/dri
      - /dev/kvm:/dev/kvm
      - /dev/snd:/dev/snd
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    volumes:
      - /dev/kvm:/dev/kvm
      - /run/user/${UID:-1000}/${WAYLAND_DISPLAY}:/run/user/${UID:-1000}/${WAYLAND_DISPLAY}:ro
      - /run/user/${UID:-1000}/pulse:/run/user/${UID:-1000}/pulse:rw
      - /run/user/${UID:-1000}/avd/running:/run/user/${UID:-1000}/avd/running:rw
      - $PWD/mount/Android:/home/manzolo/Android
      - $PWD/mount/.android:/home/manzolo/.android
      - $PWD/mount/.AndroidStudio:/home/manzolo/.AndroidStudio
      - $PWD/mount/StudioProjects:/home/manzolo/StudioProjects
      - $PWD/mount/.config/Google:/home/manzolo/.config/Google
      - $PWD/mount/.gradle:/home/manzolo/.gradle      
      - $PWD/mount/.cache/Google:/home/manzolo/.cache/Google
      - $PWD/mount/.ssh:/home/manzolo/.ssh

      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    shm_size: 2g
    security_opt:
      - seccomp=unconfined

